services:
  s3db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432

  s3admin:
    image: dpage/pgadmin4:latesta
    container_name: 68-s3-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80

  s3app:
    image: prawee/strapi:latest
    container_name: 68-s3-app
    environment:
      DATABASE_CLIENT: ${APP_CLIENT}
      DATABASE_NAME: ${APP_NAME}
      DATABASE_HOST: ${APP_DATABASE_HOST}
      DATABASE_PORT: ${APP_DATABASE_PORT}
      DATABASE_USERNAME: ${APP_USERNAME}
      DATABASE_PASSWORD: ${APP_PASSWORD}
    ports:
      - ${APP_PORT}:1337
